triglav reimport mesh/animated_cube.mesh
triglav reimport mesh/arrow.mesh
triglav reimport mesh/ball.mesh
triglav reimport mesh/bunny.mesh
triglav reimport mesh/cage.mesh
triglav reimport mesh/column.mesh
triglav reimport mesh/cone.mesh
triglav reimport mesh/cube.mesh
triglav reimport mesh/example.mesh
triglav reimport mesh/floor.mesh
triglav reimport mesh/hall.mesh
triglav reimport mesh/pine.mesh
triglav reimport mesh/sphere.mesh
triglav reimport mesh/stone_1.mesh
triglav reimport mesh/stone_2.mesh
triglav reimport mesh/table.mesh
triglav reimport mesh/teapot.mesh
triglav reimport mesh/terrain.mesh
triglav reimport mesh/tree.mesh
triglav reimport mesh/wall1.mesh
triglav reimport mesh/wall2.mesh
triglav reimport mesh/wall.mesh
triglav reimport mesh/wierdtube.mesh
